-- Gradebook column groups as data.
--
-- Until now a "group" was computed in the browser on every render (the groupedColumns memo in
-- manage/gradebook/gradebookTable.tsx and its copy in gradebook/whatIf.tsx): split the slug on
-- "-", take a prefix, and cut a new group wherever sort_order is not exactly previous + 1. This
-- migration makes a group a row, makes membership a foreign key on the column, and backfills
-- every existing gradebook so it comes out grouped.
--
-- Design, in brief (the PR description has the long form):
--   * A column is in at most one group: gradebook_columns.group_id, nullable. NULL means "not in
--     a group", which renders exactly like a group of one does today (no header).
--   * A group has no position of its own. It sits where its first member sits, and its members
--     are kept contiguous in sort_order by the two RPCs that renumber columns (reorder and
--     auto-layout). One ordering, not two that can disagree.
--   * (gradebook_id, group_id) is a composite foreign key, so a column can only ever point at a
--     group in its own gradebook, and (gradebook_id, class_id) on the group is a composite
--     foreign key to gradebooks, so the class_id that RLS reads is the gradebook's real class.
--   * Group names are unique per gradebook, case-insensitively. The table's collapse state is
--     keyed by group name, and two groups sharing a name used to collapse and expand together.

-- ---------------------------------------------------------------------------------------------
-- Schema
-- ---------------------------------------------------------------------------------------------

-- Target for the composite foreign key below. id is already unique, so this cannot fail.
CREATE UNIQUE INDEX IF NOT EXISTS gradebooks_id_class_id_key ON public.gradebooks (id, class_id);
ALTER TABLE public.gradebooks
  ADD CONSTRAINT gradebooks_id_class_id_key UNIQUE USING INDEX gradebooks_id_class_id_key;

CREATE TABLE public.gradebook_column_groups (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  class_id bigint NOT NULL,
  gradebook_id bigint NOT NULL,
  name text NOT NULL,
  CONSTRAINT gradebook_column_groups_name_not_blank CHECK (length(btrim(name)) > 0),
  CONSTRAINT gradebook_column_groups_gradebook_fkey FOREIGN KEY (gradebook_id, class_id)
    REFERENCES public.gradebooks (id, class_id) ON DELETE CASCADE,
  -- Target for gradebook_columns' composite foreign key.
  CONSTRAINT gradebook_column_groups_gradebook_id_id_key UNIQUE (gradebook_id, id)
);

COMMENT ON TABLE public.gradebook_column_groups IS
  'A named, collapsible run of gradebook columns. Membership lives on gradebook_columns.group_id; a group''s position is its first member''s sort_order.';

CREATE UNIQUE INDEX gradebook_column_groups_gradebook_name_key
  ON public.gradebook_column_groups (gradebook_id, lower(name));
CREATE INDEX gradebook_column_groups_class_id_idx ON public.gradebook_column_groups (class_id);

ALTER TABLE public.gradebook_columns ADD COLUMN group_id bigint;

COMMENT ON COLUMN public.gradebook_columns.group_id IS
  'The gradebook_column_groups row this column belongs to, or NULL for an ungrouped column. Must be a group in the same gradebook (composite foreign key).';

-- ON DELETE SET NULL (group_id): deleting a group ungroups its columns rather than deleting them,
-- and leaves gradebook_id alone (which is NOT NULL and part of the key).
ALTER TABLE public.gradebook_columns
  ADD CONSTRAINT gradebook_columns_group_fkey FOREIGN KEY (gradebook_id, group_id)
    REFERENCES public.gradebook_column_groups (gradebook_id, id) ON DELETE SET NULL (group_id);

CREATE INDEX gradebook_columns_group_id_idx ON public.gradebook_columns (group_id) WHERE group_id IS NOT NULL;

-- ---------------------------------------------------------------------------------------------
-- RLS: mirrors gradebook_columns. Instructors write; everyone in the class reads; students do
-- not see a group unless they can see at least one column in it, so a group made of staff-only
-- columns does not leak its name before release.
-- ---------------------------------------------------------------------------------------------

ALTER TABLE public.gradebook_column_groups ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.gradebook_column_groups FROM anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.gradebook_column_groups TO authenticated;
GRANT ALL ON TABLE public.gradebook_column_groups TO service_role;

CREATE POLICY "instructors CRUD"
ON public.gradebook_column_groups
AS PERMISSIVE
FOR ALL
TO authenticated
USING (public.authorizeforclassinstructor(class_id))
WITH CHECK (public.authorizeforclassinstructor(class_id));

-- (SELECT auth.uid()) is evaluated once per statement rather than once per row.
CREATE POLICY "everyone in class can view"
ON public.gradebook_column_groups
AS PERMISSIVE
FOR SELECT
TO authenticated
USING (
  EXISTS (
    SELECT 1
    FROM public.user_privileges up
    WHERE up.user_id = (SELECT auth.uid())
      AND up.class_id = gradebook_column_groups.class_id
  )
  AND (
    EXISTS (
      SELECT 1
      FROM public.user_privileges up2
      WHERE up2.user_id = (SELECT auth.uid())
        AND up2.class_id = gradebook_column_groups.class_id
        AND up2.role IN ('instructor', 'grader')
    )
    OR EXISTS (
      SELECT 1
      FROM public.gradebook_columns gc
      WHERE gc.group_id = gradebook_column_groups.id
        AND (COALESCE(gc.instructor_only, false) = false OR gc.released = true)
    )
  )
);

-- Realtime: staff channel only. The gradebook_columns broadcast sends every row to every
-- student's channel regardless of visibility; groups deliberately do not copy that, so a
-- group hidden by the policy above is not pushed to students either. Students pick up group
-- changes on their next load through RLS.
CREATE OR REPLACE FUNCTION public.broadcast_gradebook_column_groups_change()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_row public.gradebook_column_groups;
BEGIN
  IF TG_OP = 'DELETE' THEN
    v_row := OLD;
  ELSE
    v_row := NEW;
  END IF;

  PERFORM public.safe_broadcast(
    jsonb_build_object(
      'type', 'table_change',
      'operation', TG_OP,
      'table', TG_TABLE_NAME,
      'row_id', v_row.id,
      'data', to_jsonb(v_row),
      'class_id', v_row.class_id,
      'target_audience', 'staff',
      'timestamp', now()
    ),
    'broadcast',
    'class:' || v_row.class_id || ':staff',
    true
  );
  RETURN NULL;
END;
$$;

CREATE TRIGGER broadcast_gradebook_column_groups_unified
  AFTER INSERT OR UPDATE OR DELETE ON public.gradebook_column_groups
  FOR EACH ROW
  EXECUTE FUNCTION public.broadcast_gradebook_column_groups_change();

-- ---------------------------------------------------------------------------------------------
-- Keeping groups contiguous
-- ---------------------------------------------------------------------------------------------

-- Renumber a gradebook's columns 0..n-1 so that every group's members are adjacent, anchored at
-- the group's first member, keeping every other relative order. Never changes membership.
-- Callers hold the per-gradebook lock and the sort_order-trigger bypass.
CREATE OR REPLACE FUNCTION public.gradebook_columns_make_groups_contiguous(p_gradebook_id bigint)
RETURNS void
LANGUAGE sql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  WITH anchored AS (
    SELECT
      id,
      sort_order,
      CASE
        WHEN group_id IS NULL THEN sort_order
        ELSE min(sort_order) OVER (PARTITION BY group_id)
      END AS anchor
    FROM public.gradebook_columns
    WHERE gradebook_id = p_gradebook_id
  ),
  renumbered AS (
    SELECT id, (row_number() OVER (ORDER BY anchor, sort_order, id) - 1)::integer AS new_order
    FROM anchored
  )
  UPDATE public.gradebook_columns gc
  SET sort_order = r.new_order
  FROM renumbered r
  WHERE gc.id = r.id
    AND gc.sort_order IS DISTINCT FROM r.new_order;
$$;

REVOKE ALL ON FUNCTION public.gradebook_columns_make_groups_contiguous(bigint) FROM PUBLIC, anon, authenticated;

-- The rules the backfill uses to read a column's slug and name, as functions so the backfill and
-- the insert default below share one definition. Nothing at render time calls these.

-- The render-time heuristic's prefix: "assignment-<type>" for assignment-<type>-*, otherwise
-- everything before the first "-", or "other" for an empty slug.
CREATE OR REPLACE FUNCTION public.gradebook_column_family(p_slug text)
RETURNS text
LANGUAGE sql
IMMUTABLE
SET search_path = public, pg_temp
AS $$
  SELECT CASE
    WHEN split_part(p_slug, '-', 1) = 'assignment' AND cardinality(string_to_array(p_slug, '-')) >= 3
      THEN 'assignment-' || split_part(p_slug, '-', 2)
    ELSE COALESCE(NULLIF(split_part(p_slug, '-', 1), ''), 'other')
  END;
$$;

-- A column's display name without a trailing "(...)" or number: "Lab 1 (Group)" -> "Lab",
-- "Skill #12" -> "Skill", "AI Usage Log 2" -> "AI Usage Log".
CREATE OR REPLACE FUNCTION public.gradebook_column_name_stem(p_name text)
RETURNS text
LANGUAGE sql
IMMUTABLE
SET search_path = public, pg_temp
AS $$
  SELECT btrim(regexp_replace(regexp_replace(p_name, '\s*\([^)]*\)\s*$', ''), '\s*#?\s*\d+\s*$', ''));
$$;

-- The heuristic's own title for a family, used when member names don't share a stem.
CREATE OR REPLACE FUNCTION public.gradebook_column_family_title(p_family text)
RETURNS text
LANGUAGE sql
IMMUTABLE
SET search_path = public, pg_temp
AS $$
  SELECT CASE
    WHEN p_family = 'other' THEN 'Other'
    WHEN p_family LIKE 'assignment-%' THEN
      upper(left(split_part(p_family, '-', 2), 1)) || substr(split_part(p_family, '-', 2), 2)
    ELSE upper(left(p_family, 1)) || substr(p_family, 2)
  END;
$$;

-- Default group for a new column, applied once, on INSERT, and only when the insert did not say
-- which group it wants. Without it every column created after this migration would be
-- ungrouped, including the ones the assignment trigger creates, which the render-time heuristic
-- used to group as soon as a second one appeared. In order:
--
--   1. Inserted between two members of the same group: join that group ("add Quiz 3 between
--      Quiz 2 and Quiz 4"). Decided by position alone.
--   2. The column just before it is in the same family: join that column's group, or, if that
--      column is ungrouped, create a group for the two of them. This is what keeps a new
--      course's "Assignment 1, Assignment 2, ..." grouped.
--
-- Membership is never recomputed afterwards: an UPDATE never runs this, so moving or renaming a
-- column leaves its group alone, and an instructor's choice always wins.
-- Named to sort after gradebook_columns_enforce_sort_order_tr, which fills in sort_order first.
CREATE OR REPLACE FUNCTION public.gradebook_columns_inherit_group()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_before public.gradebook_columns;
  v_after_group bigint;
  v_class_id bigint;
  v_stem_before text;
  v_stem_new text;
  v_name text;
  v_candidate text;
  v_n integer := 1;
  v_group_id bigint;
BEGIN
  IF NEW.group_id IS NOT NULL OR NEW.sort_order IS NULL THEN
    RETURN NEW;
  END IF;

  SELECT * INTO v_before
  FROM public.gradebook_columns
  WHERE gradebook_id = NEW.gradebook_id AND id <> NEW.id AND sort_order < NEW.sort_order
  ORDER BY sort_order DESC, id DESC
  LIMIT 1;

  IF v_before.id IS NULL THEN
    RETURN NEW;
  END IF;

  -- 1. Between two members of one group.
  SELECT group_id INTO v_after_group
  FROM public.gradebook_columns
  WHERE gradebook_id = NEW.gradebook_id AND id <> NEW.id AND sort_order >= NEW.sort_order
  ORDER BY sort_order, id
  LIMIT 1;

  IF v_before.group_id IS NOT NULL AND v_before.group_id = v_after_group THEN
    NEW.group_id := v_before.group_id;
    RETURN NEW;
  END IF;

  -- 2. Same family as the column just before it.
  IF public.gradebook_column_family(v_before.slug) IS DISTINCT FROM public.gradebook_column_family(NEW.slug) THEN
    RETURN NEW;
  END IF;

  IF v_before.group_id IS NOT NULL THEN
    NEW.group_id := v_before.group_id;
    RETURN NEW;
  END IF;

  v_stem_before := public.gradebook_column_name_stem(v_before.name);
  v_stem_new := public.gradebook_column_name_stem(NEW.name);
  v_name := CASE
    WHEN v_stem_before = v_stem_new AND v_stem_new <> '' THEN v_stem_new
    ELSE public.gradebook_column_family_title(public.gradebook_column_family(NEW.slug))
  END;

  v_candidate := v_name;
  WHILE EXISTS (
    SELECT 1 FROM public.gradebook_column_groups
    WHERE gradebook_id = NEW.gradebook_id AND lower(name) = lower(v_candidate)
  ) LOOP
    v_n := v_n + 1;
    v_candidate := v_name || ' (' || v_n || ')';
  END LOOP;

  SELECT class_id INTO v_class_id FROM public.gradebooks WHERE id = NEW.gradebook_id;

  INSERT INTO public.gradebook_column_groups (class_id, gradebook_id, name)
  VALUES (v_class_id, NEW.gradebook_id, v_candidate)
  RETURNING id INTO v_group_id;

  UPDATE public.gradebook_columns SET group_id = v_group_id WHERE id = v_before.id;
  NEW.group_id := v_group_id;
  RETURN NEW;
END;
$$;

CREATE TRIGGER gradebook_columns_inherit_group_tr
  BEFORE INSERT ON public.gradebook_columns
  FOR EACH ROW
  EXECUTE FUNCTION public.gradebook_columns_inherit_group();

-- gradebook_columns_reorder: unchanged from 20260406120000 except the last step inside the
-- bypass window, so a drag can move a group but never tear one apart.
CREATE OR REPLACE FUNCTION public.gradebook_columns_reorder(p_ordered_column_ids bigint[])
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_gradebook_id bigint;
  v_class_id bigint;
  v_expected_count integer;
  v_payload_count integer;
  v_distinct_payload integer;
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'Not authenticated';
  END IF;

  v_payload_count := COALESCE(array_length(p_ordered_column_ids, 1), 0);

  IF v_payload_count = 0 THEN
    RETURN;
  END IF;

  SELECT COUNT(DISTINCT x) INTO v_distinct_payload
  FROM unnest(p_ordered_column_ids) AS x;

  IF v_distinct_payload <> v_payload_count THEN
    RAISE EXCEPTION 'Duplicate column IDs in reorder payload';
  END IF;

  SELECT gc.gradebook_id INTO v_gradebook_id
  FROM public.gradebook_columns AS gc
  WHERE gc.id = p_ordered_column_ids[1];

  IF v_gradebook_id IS NULL THEN
    RAISE EXCEPTION 'gradebook column % not found', p_ordered_column_ids[1];
  END IF;

  SELECT class_id INTO v_class_id
  FROM public.gradebooks
  WHERE id = v_gradebook_id;

  IF v_class_id IS NULL THEN
    RAISE EXCEPTION 'gradebook % not found', v_gradebook_id;
  END IF;

  IF NOT public.authorizeforclassinstructor(v_class_id) THEN
    RAISE EXCEPTION 'insufficient permissions: instructor access required for class %', v_class_id;
  END IF;

  SELECT COUNT(*)::integer INTO v_expected_count
  FROM public.gradebook_columns
  WHERE gradebook_id = v_gradebook_id;

  IF v_expected_count <> v_payload_count THEN
    RAISE EXCEPTION 'Payload count (%) does not match gradebook column count (%)', v_payload_count, v_expected_count;
  END IF;

  IF (
    SELECT COUNT(*)::integer
    FROM public.gradebook_columns
    WHERE gradebook_id = v_gradebook_id
      AND id = ANY (p_ordered_column_ids)
  ) <> v_payload_count THEN
    RAISE EXCEPTION 'One or more column IDs do not belong to this gradebook';
  END IF;

  -- Single-key form (bigint); the two-key form requires (integer, integer), not (int, bigint).
  -- Same namespace as gradebook_column_move_left/right; serializes all column-order updates per gradebook.
  PERFORM pg_advisory_xact_lock(v_gradebook_id);
  PERFORM set_config('pawtograder.bypass_sort_order_trigger_' || v_gradebook_id::text, 'true', true);

  BEGIN
    UPDATE public.gradebook_columns AS gc
    SET sort_order = ord.new_order
    FROM (
      SELECT id, (ordinality - 1)::integer AS new_order
      FROM unnest(p_ordered_column_ids) WITH ORDINALITY AS t(id, ordinality)
    ) AS ord
    WHERE gc.id = ord.id
      AND gc.gradebook_id = v_gradebook_id;

    PERFORM public.gradebook_columns_make_groups_contiguous(v_gradebook_id);
  EXCEPTION
    WHEN OTHERS THEN
      PERFORM set_config('pawtograder.bypass_sort_order_trigger_' || v_gradebook_id::text, 'false', true);
      RAISE;
  END;

  PERFORM set_config('pawtograder.bypass_sort_order_trigger_' || v_gradebook_id::text, 'false', true);
END;
$$;

-- gradebook_auto_layout: unchanged from 20250811000001 except the final step. Auto-layout sorts
-- by slug and then pulls computed columns after their inputs; without the last step it would
-- scatter a group whose members don't share a slug stem.
CREATE OR REPLACE FUNCTION public.gradebook_auto_layout(p_gradebook_id bigint)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE
  v_col record;
  v_dep_col_id bigint;
  v_max_dep_order integer;
  v_new_order integer;
  v_processed_ids bigint[] := '{}';
  v_remaining_count integer;
  v_prev_remaining_count integer := -1;
  v_class_id bigint;
BEGIN
  SELECT class_id INTO v_class_id
  FROM public.gradebooks
  WHERE id = p_gradebook_id;

  IF v_class_id IS NULL THEN
    RAISE EXCEPTION 'gradebook % not found', p_gradebook_id;
  END IF;

  IF NOT public.authorizeforclassinstructor(v_class_id) THEN
    RAISE EXCEPTION 'insufficient permissions: instructor access required for class %', v_class_id;
  END IF;

  PERFORM pg_advisory_xact_lock(17031, p_gradebook_id::int);
  PERFORM set_config('pawtograder.bypass_sort_order_trigger_' || p_gradebook_id::text, 'true', true);

  BEGIN
    -- Step 1: Initial alphanumeric sort by slug (lab-2 before lab-10)
    WITH ordered_cols AS (
      SELECT id, (ROW_NUMBER() OVER (ORDER BY
        regexp_replace(slug, '\d+', '', 'g'),
        COALESCE((regexp_match(slug, '\d+'))[1]::integer, 0),
        slug
      ) - 1) AS temp_sort_order
      FROM public.gradebook_columns
      WHERE gradebook_id = p_gradebook_id
    )
    UPDATE public.gradebook_columns gc
    SET sort_order = oc.temp_sort_order
    FROM ordered_cols oc
    WHERE gc.id = oc.id;

    -- Step 2: Topological sort to respect gradebook_column dependencies
    LOOP
      SELECT COUNT(*) INTO v_remaining_count
      FROM public.gradebook_columns
      WHERE gradebook_id = p_gradebook_id
        AND id <> ALL(v_processed_ids);

      EXIT WHEN v_remaining_count = 0;

      IF v_remaining_count = v_prev_remaining_count THEN
        RAISE WARNING 'Circular dependency detected in gradebook %. Stopping topological sort.', p_gradebook_id;
        EXIT;
      END IF;
      v_prev_remaining_count := v_remaining_count;

      FOR v_col IN
        SELECT id, slug, dependencies, sort_order
        FROM public.gradebook_columns
        WHERE gradebook_id = p_gradebook_id
          AND id <> ALL(v_processed_ids)
        ORDER BY sort_order NULLS LAST, id
      LOOP
        IF v_col.dependencies ? 'gradebook_columns' AND
           jsonb_array_length(v_col.dependencies->'gradebook_columns') > 0 THEN

          v_max_dep_order := -1;

          FOR v_dep_col_id IN
            SELECT jsonb_array_elements_text(v_col.dependencies->'gradebook_columns')::bigint
          LOOP
            IF v_dep_col_id = ANY(v_processed_ids) THEN
              SELECT sort_order INTO v_new_order
              FROM public.gradebook_columns
              WHERE id = v_dep_col_id AND gradebook_id = p_gradebook_id;

              IF v_new_order IS NOT NULL AND v_new_order > v_max_dep_order THEN
                v_max_dep_order := v_new_order;
              END IF;
            END IF;
          END LOOP;

          IF EXISTS (
            SELECT 1
            FROM jsonb_array_elements_text(v_col.dependencies->'gradebook_columns') AS dep_id
            WHERE dep_id::bigint <> ALL(v_processed_ids)
              AND EXISTS (
                SELECT 1 FROM public.gradebook_columns
                WHERE id = dep_id::bigint AND gradebook_id = p_gradebook_id
              )
          ) THEN
            CONTINUE;
          END IF;

          IF v_max_dep_order >= 0 THEN
            v_new_order := v_max_dep_order + 1;
            UPDATE public.gradebook_columns
            SET sort_order = v_new_order
            WHERE id = v_col.id;
          END IF;
        END IF;

        v_processed_ids := array_append(v_processed_ids, v_col.id);
      END LOOP;
    END LOOP;

    -- Final pass: compact to 0..n-1 with every group's members adjacent.
    PERFORM public.gradebook_columns_make_groups_contiguous(p_gradebook_id);

  EXCEPTION
    WHEN OTHERS THEN
      PERFORM set_config('pawtograder.bypass_sort_order_trigger_' || p_gradebook_id::text, 'false', true);
      RAISE;
  END;

  PERFORM set_config('pawtograder.bypass_sort_order_trigger_' || p_gradebook_id::text, 'false', true);
END;
$function$;

-- ---------------------------------------------------------------------------------------------
-- Backfill
--
-- Reads slugs, names and dependencies once per gradebook, so nothing has to read them at render
-- time again. It is a function rather than inline SQL for one reason: a gradebook that exists
-- before this migration is backfilled by the migration, but `supabase db reset` replays
-- migrations into an empty database and seeds afterwards, and the seed has to leave its class
-- in the same state a pre-existing course would be in. scripts/DatabaseSeedingUtils.ts calls it
-- once, after it has created its columns. The app never calls it; only service_role can.
--
-- It only touches gradebooks that have no groups yet, so running it twice is a no-op and it
-- can never overwrite a grouping an instructor has since edited.
--
-- It starts from exactly what the render-time heuristic produced and departs from it only where
-- the heuristic was wrong; each departure is labelled (F1..F4) and listed in the PR.
--
--   1. Order each gradebook's columns by (sort_order, id) and give each a position 1..n.
--   2. Family = the heuristic's prefix: "assignment-<type>" for assignment-<type>-*, otherwise
--      everything before the first "-".
--   3. A family run is consecutive positions with the same family. The heuristic also cut a run
--      wherever sort_order skipped a value; positions don't, so a hole left by a deleted column
--      no longer splits a family in two (F1).
--   4. Columns left on their own after step 3 that are computed from exactly the same set of
--      columns, and sit next to each other, form one run (F4).
--   5. Every run of two or more columns becomes a group. A run of one stays ungrouped, which is
--      what it rendered as.
--   6. Name: the common stem of the member columns' display names (minus a trailing "(...)" and
--      number), so "AI Usage Log 1/2" gives "AI Usage Log", not "Ai" (F3). Failing that, the
--      heuristic's own title. A run of computed columns is named after the group its inputs
--      are all in ("Skill summary"), failing that "Summary".
--   7. Names are unique per gradebook: a family interrupted by some other column stays two
--      groups, because merging them would move columns, but the second is "Quiz (2)" and no
--      longer shares the first one's collapse state (F2).
--
-- Policy for rows it can't classify: none are dropped and none are moved. A column whose slug
-- has no "-" is its own family, exactly as before, and anything that ends up alone is
-- ungrouped. The backfill never changes sort_order.
-- ---------------------------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.gradebook_column_groups_backfill(p_gradebook_id bigint DEFAULT NULL)
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_created integer;
BEGIN
  DROP TABLE IF EXISTS _gcg_columns, _gcg_runs, _gcg_groups;

  CREATE TEMP TABLE _gcg_columns AS
  SELECT
    gc.id,
    gc.gradebook_id,
    g.class_id,
    row_number() OVER (PARTITION BY gc.gradebook_id ORDER BY COALESCE(gc.sort_order, 0), gc.id) AS pos,
    public.gradebook_column_family(gc.slug) AS family,
    (
      SELECT array_agg(DISTINCT d::bigint ORDER BY d::bigint)
      FROM jsonb_array_elements_text(
        CASE WHEN jsonb_typeof(gc.dependencies -> 'gradebook_columns') = 'array'
          THEN gc.dependencies -> 'gradebook_columns' END
      ) AS d
    ) AS deps,
    public.gradebook_column_name_stem(gc.name) AS stem
  FROM public.gradebook_columns gc
  JOIN public.gradebooks g ON g.id = gc.gradebook_id
  WHERE (p_gradebook_id IS NULL OR gc.gradebook_id = p_gradebook_id)
    AND NOT EXISTS (SELECT 1 FROM public.gradebook_column_groups x WHERE x.gradebook_id = gc.gradebook_id);

  -- Steps 3 and 4. A unit is a family run (if it has 2+ members), a set of inputs (for a lone
  -- computed column), or the column itself; consecutive columns with the same unit key are a run.
  CREATE TEMP TABLE _gcg_runs AS
  WITH family_runs AS (
    SELECT
      x.*,
      sum(CASE WHEN x.family IS DISTINCT FROM x.prev_family THEN 1 ELSE 0 END)
        OVER (PARTITION BY x.gradebook_id ORDER BY x.pos) AS family_run
    FROM (
      SELECT c.*, lag(c.family) OVER (PARTITION BY c.gradebook_id ORDER BY c.pos) AS prev_family
      FROM _gcg_columns c
    ) x
  ),
  units AS (
    SELECT
      fr.*,
      CASE
        WHEN count(*) OVER (PARTITION BY fr.gradebook_id, fr.family_run) > 1 THEN 'family:' || fr.family_run
        WHEN fr.deps IS NOT NULL THEN 'derived:' || fr.deps::text
        ELSE 'column:' || fr.id
      END AS unit_key
    FROM family_runs fr
  ),
  runs AS (
    SELECT
      k.*,
      sum(CASE WHEN k.unit_key IS DISTINCT FROM k.prev_unit_key THEN 1 ELSE 0 END)
        OVER (PARTITION BY k.gradebook_id ORDER BY k.pos) AS run
    FROM (
      SELECT u.*, lag(u.unit_key) OVER (PARTITION BY u.gradebook_id ORDER BY u.pos) AS prev_unit_key
      FROM units u
    ) k
  )
  SELECT r.*, count(*) OVER (PARTITION BY r.gradebook_id, r.run) AS run_size
  FROM runs r;

  -- Steps 5 and 6.
  CREATE TEMP TABLE _gcg_groups AS
  SELECT
    r.gradebook_id,
    min(r.class_id) AS class_id,
    r.run,
    min(r.pos) AS first_pos,
    bool_or(r.unit_key LIKE 'derived:%') AS is_derived,
    CASE
      WHEN count(DISTINCT r.stem) = 1 AND min(r.stem) <> '' THEN min(r.stem)
      ELSE public.gradebook_column_family_title(min(r.family))
    END AS name
  FROM _gcg_runs r
  WHERE r.run_size > 1
  GROUP BY r.gradebook_id, r.run;

  -- A run of computed columns is named after the one non-derived group all of its inputs are in.
  UPDATE _gcg_groups dg
  SET name = COALESCE(
    (
      SELECT src.name || ' summary'
      FROM _gcg_runs m
      CROSS JOIN LATERAL unnest(m.deps) AS dep(id)
      JOIN _gcg_runs d ON d.id = dep.id
      JOIN _gcg_groups src ON src.gradebook_id = d.gradebook_id AND src.run = d.run AND NOT src.is_derived
      WHERE m.gradebook_id = dg.gradebook_id AND m.run = dg.run
      GROUP BY src.name
      HAVING count(*) = (
        SELECT count(*) FROM _gcg_runs m2 CROSS JOIN LATERAL unnest(m2.deps)
        WHERE m2.gradebook_id = dg.gradebook_id AND m2.run = dg.run
      )
    ),
    'Summary'
  )
  WHERE dg.is_derived;

  -- Step 7.
  UPDATE _gcg_groups g
  SET name = g.name || ' (' || n.nth || ')'
  FROM (
    SELECT gradebook_id, run, row_number() OVER (PARTITION BY gradebook_id, lower(name) ORDER BY first_pos) AS nth
    FROM _gcg_groups
  ) n
  WHERE n.gradebook_id = g.gradebook_id AND n.run = g.run AND n.nth > 1;

  INSERT INTO public.gradebook_column_groups (class_id, gradebook_id, name)
  SELECT class_id, gradebook_id, name
  FROM _gcg_groups
  ORDER BY gradebook_id, first_pos;
  GET DIAGNOSTICS v_created = ROW_COUNT;

  UPDATE public.gradebook_columns gc
  SET group_id = cg.id
  FROM _gcg_runs r
  JOIN _gcg_groups g ON g.gradebook_id = r.gradebook_id AND g.run = r.run
  JOIN public.gradebook_column_groups cg ON cg.gradebook_id = g.gradebook_id AND lower(cg.name) = lower(g.name)
  WHERE gc.id = r.id;

  DROP TABLE _gcg_columns, _gcg_runs, _gcg_groups;
  RETURN v_created;
END;
$$;

REVOKE ALL ON FUNCTION public.gradebook_column_groups_backfill(bigint) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.gradebook_column_groups_backfill(bigint) TO service_role;

-- Every gradebook that exists now. The column broadcast trigger is suspended for this one call:
-- it would send one realtime message per column per student in every course, and clients
-- running the previous frontend don't read group_id anyway. Every other trigger (audit,
-- updated_at, cache invalidation) still fires.
ALTER TABLE public.gradebook_columns DISABLE TRIGGER broadcast_gradebook_columns_unified;
SELECT public.gradebook_column_groups_backfill();
ALTER TABLE public.gradebook_columns ENABLE TRIGGER broadcast_gradebook_columns_unified;
