-- Gradebook column groups as data.
--
-- Until now a "group" was computed in the browser on every render (the groupedColumns memo in
-- manage/gradebook/gradebookTable.tsx and its copy in gradebook/whatIf.tsx): split the slug on
-- "-", take a prefix, and cut a new group wherever sort_order is not exactly previous + 1. This
-- migration makes a group a row, makes membership a foreign key on the column, and backfills
-- every existing gradebook so it comes out grouped. 20260924045931_gradebook_column_groups_crud
-- adds the RPCs instructors use to edit groups.
--
-- Design, in brief (the PR description has the long form):
--   * A column is in at most one group: gradebook_columns.group_id, nullable. NULL means "not in
--     a group".
--   * A group has no position of its own. It sits where its first member sits. Every function
--     here that writes sort_order keeps a group's members adjacent, and a write that makes a
--     column join a group repairs the order if it split one. One ordering, not two that can
--     disagree.
--   * (gradebook_id, group_id) is a composite foreign key, so a column can only ever point at a
--     group in its own gradebook, and (gradebook_id, class_id) on the group is a composite
--     foreign key to gradebooks, so the class_id that RLS reads is the gradebook's real class.
--   * Group names are unique per gradebook, case-insensitively, and have no leading or trailing
--     whitespace.
--   * A group always has at least one column: it is deleted when its last column leaves, and a
--     new group must have a column by the end of the transaction that created it.

-- ---------------------------------------------------------------------------------------------
-- Schema
-- ---------------------------------------------------------------------------------------------

-- Target for the composite foreign key below. id is already unique, so this cannot fail.
CREATE UNIQUE INDEX IF NOT EXISTS gradebooks_id_class_id_key ON public.gradebooks (id, class_id);
ALTER TABLE public.gradebooks
  ADD CONSTRAINT gradebooks_id_class_id_key UNIQUE USING INDEX gradebooks_id_class_id_key;

CREATE TABLE public.gradebook_column_groups (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  class_id bigint NOT NULL,
  gradebook_id bigint NOT NULL,
  name text NOT NULL,
  -- Something to show, and no whitespace at either end, so " Quiz" can't sit beside "Quiz".
  CONSTRAINT gradebook_column_groups_name_trimmed CHECK (name ~ '\S' AND name !~ '^\s' AND name !~ '\s$'),
  CONSTRAINT gradebook_column_groups_gradebook_fkey FOREIGN KEY (gradebook_id, class_id)
    REFERENCES public.gradebooks (id, class_id) ON DELETE CASCADE,
  -- Target for gradebook_columns' composite foreign key.
  CONSTRAINT gradebook_column_groups_gradebook_id_id_key UNIQUE (gradebook_id, id)
);

COMMENT ON TABLE public.gradebook_column_groups IS
  'A named, collapsible run of gradebook columns. Membership lives on gradebook_columns.group_id; a group''s position is its first member''s sort_order.';

CREATE UNIQUE INDEX gradebook_column_groups_gradebook_name_key
  ON public.gradebook_column_groups (gradebook_id, lower(name));

-- updated_at lets clients catch up incrementally (TableController's watermark refetch).
CREATE TRIGGER set_updated_at_on_gradebook_column_groups
  BEFORE UPDATE ON public.gradebook_column_groups
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

ALTER TABLE public.gradebook_columns ADD COLUMN group_id bigint;

COMMENT ON COLUMN public.gradebook_columns.group_id IS
  'The gradebook_column_groups row this column belongs to, or NULL for an ungrouped column. Must be a group in the same gradebook (composite foreign key).';

-- ON DELETE SET NULL (group_id): deleting a group ungroups its columns rather than deleting them,
-- and leaves gradebook_id alone (which is NOT NULL and part of the key).
ALTER TABLE public.gradebook_columns
  ADD CONSTRAINT gradebook_columns_group_fkey FOREIGN KEY (gradebook_id, group_id)
    REFERENCES public.gradebook_column_groups (gradebook_id, id) ON DELETE SET NULL (group_id);

CREATE INDEX gradebook_columns_group_id_idx ON public.gradebook_columns (group_id) WHERE group_id IS NOT NULL;

-- ---------------------------------------------------------------------------------------------
-- Privileges and RLS. Policies mirror gradebook_columns: instructors write, everyone in the
-- class reads. Signed-in users can read, rename and delete groups directly; creating a group and
-- changing membership go through the RPCs in 20260924045931, which keep the order intact.
-- ---------------------------------------------------------------------------------------------

ALTER TABLE public.gradebook_column_groups ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.gradebook_column_groups FROM PUBLIC, anon, authenticated;
GRANT SELECT, DELETE ON TABLE public.gradebook_column_groups TO authenticated;
GRANT UPDATE (name) ON TABLE public.gradebook_column_groups TO authenticated;
GRANT ALL ON TABLE public.gradebook_column_groups TO service_role;

CREATE POLICY "instructors CRUD"
ON public.gradebook_column_groups
AS PERMISSIVE
FOR ALL
TO authenticated
USING (public.authorizeforclassinstructor(class_id))
WITH CHECK (public.authorizeforclassinstructor(class_id));

-- A class member sees a group if they are staff, or if they can see at least one column in it.
-- The inner query runs under gradebook_columns' own RLS, so "can see a column" means exactly
-- what it means for columns (including the instructor_only / released rule), with no second
-- copy of that rule to drift. (SELECT auth.uid()) is evaluated once per statement.
CREATE POLICY "everyone in class can view"
ON public.gradebook_column_groups
AS PERMISSIVE
FOR SELECT
TO authenticated
USING (
  EXISTS (
    SELECT 1
    FROM public.user_privileges up
    WHERE up.user_id = (SELECT auth.uid())
      AND up.class_id = gradebook_column_groups.class_id
  )
  AND (
    EXISTS (
      SELECT 1
      FROM public.user_privileges up2
      WHERE up2.user_id = (SELECT auth.uid())
        AND up2.class_id = gradebook_column_groups.class_id
        AND up2.role IN ('instructor', 'grader')
    )
    OR EXISTS (
      SELECT 1
      FROM public.gradebook_columns gc
      WHERE gc.group_id = gradebook_column_groups.id
    )
  )
);

-- Realtime: staff channel only. A group hidden by the policy above is not pushed to students
-- either. Students pick up group changes on their next load through RLS.
CREATE OR REPLACE FUNCTION public.broadcast_gradebook_column_groups_change()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_row public.gradebook_column_groups;
BEGIN
  IF TG_OP = 'DELETE' THEN
    v_row := OLD;
  ELSE
    v_row := NEW;
  END IF;

  PERFORM public.safe_broadcast(
    jsonb_build_object(
      'type', 'table_change',
      'operation', TG_OP,
      'table', TG_TABLE_NAME,
      'row_id', v_row.id,
      'data', to_jsonb(v_row),
      'class_id', v_row.class_id,
      'target_audience', 'staff',
      'timestamp', now()
    ),
    'broadcast',
    'class:' || v_row.class_id || ':staff',
    true
  );
  RETURN NULL;
END;
$$;

CREATE TRIGGER broadcast_gradebook_column_groups_unified
  AFTER INSERT OR UPDATE OR DELETE ON public.gradebook_column_groups
  FOR EACH ROW
  EXECUTE FUNCTION public.broadcast_gradebook_column_groups_change();

-- ---------------------------------------------------------------------------------------------
-- A group always has a column
-- ---------------------------------------------------------------------------------------------

-- A group with no columns has no position (it sits where its first member is), so it would be
-- invisible and still hold its name. Delete it as soon as its last column leaves or is deleted.
CREATE OR REPLACE FUNCTION public.gradebook_column_groups_drop_empty()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
  DELETE FROM public.gradebook_column_groups g
  WHERE g.id = OLD.group_id
    AND NOT EXISTS (SELECT 1 FROM public.gradebook_columns gc WHERE gc.group_id = OLD.group_id);
  RETURN NULL;
END;
$$;

CREATE TRIGGER gradebook_columns_drop_empty_group_tr
  AFTER UPDATE OF group_id OR DELETE ON public.gradebook_columns
  FOR EACH ROW
  WHEN (OLD.group_id IS NOT NULL)
  EXECUTE FUNCTION public.gradebook_column_groups_drop_empty();

-- The other direction: a group has to have a column by the time the transaction that created it
-- commits. Deferred, because a group is always created first and given its columns after.
CREATE OR REPLACE FUNCTION public.gradebook_column_groups_require_member()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
  IF EXISTS (SELECT 1 FROM public.gradebook_column_groups WHERE id = NEW.id)
     AND NOT EXISTS (SELECT 1 FROM public.gradebook_columns WHERE group_id = NEW.id) THEN
    RAISE EXCEPTION 'Column group "%" has no columns', NEW.name
      USING ERRCODE = 'check_violation',
            HINT = 'Create a group together with its columns (gradebook_column_group_create).';
  END IF;
  RETURN NULL;
END;
$$;

CREATE CONSTRAINT TRIGGER gradebook_column_groups_require_member_tr
  AFTER INSERT ON public.gradebook_column_groups
  DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW
  EXECUTE FUNCTION public.gradebook_column_groups_require_member();

-- ---------------------------------------------------------------------------------------------
-- Column order: one definition, one way to write it
-- ---------------------------------------------------------------------------------------------

-- Columns in the order the gradebook draws them. Each column belongs to a unit: a whole group
-- ('g' || group_id) or an ungrouped column ('c' || id). Units are ordered by their first column,
-- by (sort_order, id), and a group's columns follow each other in the same order. NULL
-- sort_order counts as 0, as it does in the client (lib/gradebookColumnGroups.ts). Ordering units
-- by their first column's (sort_order, id), rather than by sort_order alone, is what stops a tie
-- between a group and an ungrouped column from interleaving them.
CREATE OR REPLACE FUNCTION public.gradebook_columns_display_order(p_gradebook_id bigint)
RETURNS TABLE (id bigint, group_id bigint, pos bigint, unit text)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  SELECT
    a.id,
    a.group_id,
    row_number() OVER (ORDER BY a.anchor_sort, a.anchor_id, a.sort_order, a.id) AS pos,
    a.unit
  FROM (
    SELECT
      c.id,
      c.group_id,
      c.sort_order,
      c.unit,
      first_value(c.sort_order) OVER w AS anchor_sort,
      first_value(c.id) OVER w AS anchor_id
    FROM (
      SELECT
        gc.id,
        gc.group_id,
        COALESCE(gc.sort_order, 0) AS sort_order,
        COALESCE('g' || gc.group_id, 'c' || gc.id) AS unit
      FROM public.gradebook_columns gc
      WHERE gc.gradebook_id = p_gradebook_id
    ) c
    WINDOW w AS (PARTITION BY c.unit ORDER BY c.sort_order, c.id)
  ) a
  ORDER BY pos;
$$;

-- True if some group's members are not next to each other in (sort_order, id) order.
CREATE OR REPLACE FUNCTION public.gradebook_column_groups_torn(p_gradebook_id bigint)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM (
      SELECT group_id, row_number() OVER (ORDER BY COALESCE(sort_order, 0), id) AS rn
      FROM public.gradebook_columns
      WHERE gradebook_id = p_gradebook_id
    ) o
    WHERE o.group_id IS NOT NULL
    GROUP BY o.group_id
    HAVING max(o.rn) - min(o.rn) + 1 <> count(*)
  );
$$;

-- The message for "these columns moved": up to 49 row ids, or a refetch signal for 50 or more.
CREATE OR REPLACE FUNCTION public.gradebook_columns_order_payload(p_class_id bigint, p_column_ids bigint[], p_audience text)
RETURNS jsonb
LANGUAGE sql
STABLE
SET search_path = public, pg_temp
AS $$
  SELECT jsonb_build_object(
    'type', 'table_change',
    'operation', 'UPDATE',
    'table', 'gradebook_columns',
    'class_id', p_class_id,
    'affected_count', cardinality(p_column_ids),
    'target_audience', p_audience,
    'timestamp', now()
  ) || CASE
    WHEN cardinality(p_column_ids) >= 50 THEN jsonb_build_object('requires_refetch', true)
    ELSE jsonb_build_object('row_ids', to_jsonb(p_column_ids), 'requires_refetch', false)
  END;
$$;

-- Tell clients that some columns moved: one message per channel, in the shape of the
-- statement-level broadcasts in 20251102112812_reduce-rt-spam (up to 49 row ids, or a refetch
-- signal for 50 or more). The row-level column broadcast would send every moved row to every
-- student, which for one "move this 100-column group" is 200 rows times the class size. Clients
-- refetch the ids through RLS, so a student is never sent a staff-only column's data.
CREATE OR REPLACE FUNCTION public.gradebook_columns_broadcast_order(p_gradebook_id bigint, p_column_ids bigint[])
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_class_id bigint;
  v_student_ids bigint[];
  v_student_payload jsonb;
  v_profile_id uuid;
BEGIN
  IF COALESCE(cardinality(p_column_ids), 0) = 0 THEN
    RETURN;
  END IF;

  SELECT class_id INTO v_class_id FROM public.gradebooks WHERE id = p_gradebook_id;
  IF v_class_id IS NULL THEN
    RETURN;
  END IF;

  PERFORM public.safe_broadcast(
    public.gradebook_columns_order_payload(v_class_id, p_column_ids, 'staff'),
    'broadcast',
    'class:' || v_class_id || ':staff',
    true
  );

  -- Students hear only about columns they can see (the gradebook_columns RLS rule).
  SELECT array_agg(gc.id ORDER BY gc.id) INTO v_student_ids
  FROM public.gradebook_columns gc
  WHERE gc.id = ANY (p_column_ids)
    AND (COALESCE(gc.instructor_only, false) = false OR gc.released = true);

  IF COALESCE(cardinality(v_student_ids), 0) = 0 THEN
    RETURN;
  END IF;

  v_student_payload := public.gradebook_columns_order_payload(v_class_id, v_student_ids, 'user');
  FOR v_profile_id IN
    SELECT ur.private_profile_id FROM public.user_roles ur WHERE ur.class_id = v_class_id AND ur.role = 'student'
  LOOP
    PERFORM public.safe_broadcast(
      v_student_payload,
      'broadcast',
      'class:' || v_class_id || ':user:' || v_profile_id,
      true
    );
  END LOOP;
END;
$$;

-- The row-level column broadcast, from 20250929004834, with two changes:
--   * Rows written by gradebook_columns_write_order are announced by
--     gradebook_columns_broadcast_order instead (one message per channel).
--   * Students are only sent columns they can see, by the same rule as gradebook_columns' RLS
--     (not instructor_only, or released). It used to send every column, staff-only ones
--     included, to every student's channel. A column that stops being visible (or is deleted
--     while visible) is sent to students as a DELETE carrying only its id.
CREATE OR REPLACE FUNCTION public.broadcast_gradebook_columns_change()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE
    target_class_id BIGINT;
    staff_payload JSONB;
    user_payload JSONB;
    affected_profile_ids UUID[];
    profile_id UUID;
    visible_before BOOLEAN := false;
    visible_after BOOLEAN := false;
BEGIN
    IF TG_OP = 'UPDATE'
       AND current_setting('pawtograder.batch_column_broadcast_' || NEW.gradebook_id, true) = 'true' THEN
        RETURN NEW;
    END IF;

    IF TG_OP IN ('UPDATE', 'DELETE') THEN
        visible_before := COALESCE(OLD.instructor_only, false) = false OR OLD.released = true;
    END IF;
    IF TG_OP IN ('INSERT', 'UPDATE') THEN
        visible_after := COALESCE(NEW.instructor_only, false) = false OR NEW.released = true;
    END IF;

    -- Get the class_id from the record
    IF TG_OP = 'INSERT' THEN
        target_class_id := NEW.class_id;
    ELSIF TG_OP = 'UPDATE' THEN
        target_class_id := COALESCE(NEW.class_id, OLD.class_id);
    ELSIF TG_OP = 'DELETE' THEN
        target_class_id := OLD.class_id;
    END IF;

    IF target_class_id IS NOT NULL THEN
        -- Create payload for gradebook_columns changes
        staff_payload := jsonb_build_object(
            'type', 'table_change',
            'operation', TG_OP,
            'table', TG_TABLE_NAME,
            'row_id', CASE
                WHEN TG_OP = 'DELETE' THEN OLD.id
                ELSE NEW.id
            END,
            'data', CASE
                WHEN TG_OP = 'DELETE' THEN to_jsonb(OLD)
                ELSE to_jsonb(NEW)
            END,
            'class_id', target_class_id,
            'target_audience', 'staff',
            'timestamp', NOW()
        );

        -- Broadcast to staff channel (instructors and graders see all column changes)
        PERFORM public.safe_broadcast(
            staff_payload,
            'broadcast',
            'class:' || target_class_id || ':staff',
            true
        );

        IF visible_after THEN
            -- Same as staff but marked for users
            user_payload := staff_payload || jsonb_build_object('target_audience', 'user');
        ELSIF visible_before THEN
            user_payload := jsonb_build_object(
                'type', 'table_change',
                'operation', 'DELETE',
                'table', TG_TABLE_NAME,
                'row_id', CASE WHEN TG_OP = 'DELETE' THEN OLD.id ELSE NEW.id END,
                'class_id', target_class_id,
                'target_audience', 'user',
                'timestamp', NOW()
            );
        END IF;

        IF user_payload IS NOT NULL THEN
            -- Get all students in the class for user channels
            SELECT ARRAY(
                SELECT ur.private_profile_id
                FROM public.user_roles ur
                WHERE ur.class_id = target_class_id AND ur.role = 'student'
            ) INTO affected_profile_ids;

            FOREACH profile_id IN ARRAY affected_profile_ids
            LOOP
                PERFORM public.safe_broadcast(
                    user_payload,
                    'broadcast',
                    'class:' || target_class_id || ':user:' || profile_id,
                    true
                );
            END LOOP;
        END IF;
    END IF;

    -- Return the appropriate record
    IF TG_OP = 'DELETE' THEN
        RETURN OLD;
    ELSE
        RETURN NEW;
    END IF;
END;
$function$;

-- Write a left-to-right order (sort_order 0..n-1 in array order), touching only rows whose
-- sort_order changes, and return their ids. Turns off the sort_order trigger's shifting and the
-- row-level broadcast for the duration, and restores both flags to what they were, so callers
-- never have to set them. Does not broadcast: the caller does, once.
CREATE OR REPLACE FUNCTION public.gradebook_columns_write_order(p_gradebook_id bigint, p_ordered_ids bigint[])
RETURNS bigint[]
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_bypass_key text := 'pawtograder.bypass_sort_order_trigger_' || p_gradebook_id;
  v_batch_key text := 'pawtograder.batch_column_broadcast_' || p_gradebook_id;
  v_prev_bypass text := COALESCE(NULLIF(current_setting(v_bypass_key, true), ''), 'false');
  v_prev_batch text := COALESCE(NULLIF(current_setting(v_batch_key, true), ''), 'false');
  v_changed bigint[];
BEGIN
  PERFORM set_config(v_bypass_key, 'true', true);
  PERFORM set_config(v_batch_key, 'true', true);

  WITH updated AS (
    UPDATE public.gradebook_columns gc
    SET sort_order = (t.ord - 1)::integer
    FROM unnest(p_ordered_ids) WITH ORDINALITY AS t(id, ord)
    WHERE gc.id = t.id
      AND gc.gradebook_id = p_gradebook_id
      AND gc.sort_order IS DISTINCT FROM (t.ord - 1)::integer
    RETURNING gc.id
  )
  SELECT COALESCE(array_agg(id), '{}') INTO v_changed FROM updated;

  PERFORM set_config(v_bypass_key, v_prev_bypass, true);
  PERFORM set_config(v_batch_key, v_prev_batch, true);
  RETURN v_changed;
END;
$$;

-- Renumber a gradebook's columns 0..n-1 in display order, so every group's members are adjacent,
-- keeping every other relative order. Never changes membership. Returns the ids it moved.
CREATE OR REPLACE FUNCTION public.gradebook_columns_make_groups_contiguous(p_gradebook_id bigint)
RETURNS bigint[]
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
  RETURN public.gradebook_columns_write_order(
    p_gradebook_id,
    (SELECT array_agg(d.id ORDER BY d.pos) FROM public.gradebook_columns_display_order(p_gradebook_id) d)
  );
END;
$$;

-- Write a full left-to-right order, close up any group it split, and tell clients once.
-- Callers check authorization and hold pg_advisory_xact_lock(gradebook_id).
CREATE OR REPLACE FUNCTION public.gradebook_columns_apply_order(p_gradebook_id bigint, p_ordered_ids bigint[])
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_changed bigint[];
BEGIN
  v_changed := public.gradebook_columns_write_order(p_gradebook_id, p_ordered_ids);
  IF public.gradebook_column_groups_torn(p_gradebook_id) THEN
    v_changed := v_changed || public.gradebook_columns_make_groups_contiguous(p_gradebook_id);
  END IF;
  PERFORM public.gradebook_columns_broadcast_order(
    p_gradebook_id,
    ARRAY(SELECT DISTINCT x FROM unnest(v_changed) AS x ORDER BY x)
  );
END;
$$;

-- A write that puts a column into a group (an INSERT with group_id, or an UPDATE that changes
-- it) without going through the RPCs can leave the group split. Repair it after the statement.
-- Skipped while a function is managing the order itself (it holds the sort_order bypass), and
-- for statements nested inside other triggers. Writes that only change sort_order are left to
-- the RPCs: the seed's renumbering splits groups on its way to a layout, and repairing each step
-- would change the layout it arrives at.
CREATE OR REPLACE FUNCTION public.gradebook_columns_repair_group_order()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_gradebook_id bigint;
  v_gradebook_ids bigint[];
BEGIN
  IF pg_trigger_depth() > 1 THEN
    RETURN NULL;
  END IF;

  IF TG_OP = 'INSERT' THEN
    SELECT array_agg(DISTINCT n.gradebook_id) INTO v_gradebook_ids
    FROM new_table n
    WHERE n.group_id IS NOT NULL;
  ELSE
    SELECT array_agg(DISTINCT n.gradebook_id) INTO v_gradebook_ids
    FROM new_table n
    JOIN old_table o ON o.id = n.id
    WHERE n.group_id IS NOT NULL
      AND n.group_id IS DISTINCT FROM o.group_id;
  END IF;

  FOREACH v_gradebook_id IN ARRAY COALESCE(v_gradebook_ids, '{}')
  LOOP
    CONTINUE WHEN current_setting('pawtograder.bypass_sort_order_trigger_' || v_gradebook_id, true) = 'true';
    CONTINUE WHEN NOT public.gradebook_column_groups_torn(v_gradebook_id);
    PERFORM pg_advisory_xact_lock(v_gradebook_id);
    PERFORM public.gradebook_columns_broadcast_order(
      v_gradebook_id,
      public.gradebook_columns_make_groups_contiguous(v_gradebook_id)
    );
  END LOOP;

  RETURN NULL;
END;
$$;

CREATE TRIGGER gradebook_columns_repair_groups_insert_tr
  AFTER INSERT ON public.gradebook_columns
  REFERENCING NEW TABLE AS new_table
  FOR EACH STATEMENT
  EXECUTE FUNCTION public.gradebook_columns_repair_group_order();

CREATE TRIGGER gradebook_columns_repair_groups_update_tr
  AFTER UPDATE ON public.gradebook_columns
  REFERENCING OLD TABLE AS old_table NEW TABLE AS new_table
  FOR EACH STATEMENT
  EXECUTE FUNCTION public.gradebook_columns_repair_group_order();

-- ---------------------------------------------------------------------------------------------
-- Reading slugs and names, for the backfill and the insert-time default only
-- ---------------------------------------------------------------------------------------------

-- Every kind of whitespace off both ends. The name CHECK on gradebook_column_groups rejects
-- exactly what this would remove.
CREATE OR REPLACE FUNCTION public.gradebook_column_group_clean_name(p_name text)
RETURNS text
LANGUAGE sql
IMMUTABLE
SET search_path = public, pg_temp
AS $$
  SELECT regexp_replace(p_name, '^\s+|\s+$', '', 'g');
$$;

-- The render-time heuristic's prefix: "assignment-<type>" for assignment-<type>-*, otherwise
-- everything before the first "-", or "other" for an empty slug. One departure (F8): the
-- heuristic put every two-part assignment slug (the assignment trigger's "assignment-<slug>" for
-- an assignment slug with no "-") into one "assignment" family, so "assignment-hw1" grouped with
-- "assignment-final". Here the assignment's own slug, minus a trailing number, is the type:
-- "assignment-hw1" and "assignment-hw2" are family "assignment-hw", "assignment-final" is
-- "assignment-final".
CREATE OR REPLACE FUNCTION public.gradebook_column_family(p_slug text)
RETURNS text
LANGUAGE sql
IMMUTABLE
SET search_path = public, pg_temp
AS $$
  SELECT CASE
    WHEN split_part(p_slug, '-', 1) = 'assignment' AND cardinality(string_to_array(p_slug, '-')) >= 3
      THEN 'assignment-' || split_part(p_slug, '-', 2)
    WHEN split_part(p_slug, '-', 1) = 'assignment' AND cardinality(string_to_array(p_slug, '-')) = 2
         AND regexp_replace(split_part(p_slug, '-', 2), '[0-9]+$', '') <> ''
      THEN 'assignment-' || regexp_replace(split_part(p_slug, '-', 2), '[0-9]+$', '')
    ELSE COALESCE(NULLIF(split_part(p_slug, '-', 1), ''), 'other')
  END;
$$;

-- A column's display name without a trailing "(...)" or number: "Lab 1 (Group)" -> "Lab",
-- "Skill #12" -> "Skill", "AI Usage Log 2" -> "AI Usage Log".
CREATE OR REPLACE FUNCTION public.gradebook_column_name_stem(p_name text)
RETURNS text
LANGUAGE sql
IMMUTABLE
SET search_path = public, pg_temp
AS $$
  SELECT public.gradebook_column_group_clean_name(
    regexp_replace(regexp_replace(p_name, '\s*\([^)]*\)\s*$', ''), '\s*#?\s*\d+\s*$', '')
  );
$$;

-- The heuristic's own title for a family, used when member names don't share a stem.
CREATE OR REPLACE FUNCTION public.gradebook_column_family_title(p_family text)
RETURNS text
LANGUAGE sql
IMMUTABLE
SET search_path = public, pg_temp
AS $$
  SELECT CASE
    WHEN f = '' OR f = 'other' THEN 'Other'
    WHEN f LIKE 'assignment-%' THEN
      upper(left(split_part(f, '-', 2), 1)) || substr(split_part(f, '-', 2), 2)
    ELSE upper(left(f, 1)) || substr(f, 2)
  END
  FROM (SELECT public.gradebook_column_group_clean_name(p_family) AS f) AS cleaned;
$$;

-- The first free name in a gradebook: p_name if nobody has it (case-insensitively), otherwise
-- "p_name (2)", "p_name (3)", and so on. A blank name becomes "Group".
CREATE OR REPLACE FUNCTION public.gradebook_column_group_free_name(p_gradebook_id bigint, p_name text)
RETURNS text
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_base text := COALESCE(NULLIF(public.gradebook_column_group_clean_name(p_name), ''), 'Group');
  v_candidate text := v_base;
  v_n integer := 1;
BEGIN
  WHILE EXISTS (
    SELECT 1 FROM public.gradebook_column_groups
    WHERE gradebook_id = p_gradebook_id AND lower(name) = lower(v_candidate)
  ) LOOP
    v_n := v_n + 1;
    v_candidate := v_base || ' (' || v_n || ')';
  END LOOP;
  RETURN v_candidate;
END;
$$;

-- The integer column ids in a column's dependencies->'gradebook_columns'. Anything that is not a
-- whole number is skipped rather than allowed to fail a cast.
CREATE OR REPLACE FUNCTION public.gradebook_column_dependency_ids(p_dependencies jsonb)
RETURNS bigint[]
LANGUAGE sql
IMMUTABLE
SET search_path = public, pg_temp
AS $$
  SELECT array_agg(DISTINCT d::bigint ORDER BY d::bigint)
  FROM jsonb_array_elements_text(
    CASE WHEN jsonb_typeof(p_dependencies -> 'gradebook_columns') = 'array'
      THEN p_dependencies -> 'gradebook_columns' END
  ) AS d
  WHERE d ~ '^[0-9]{1,18}$';
$$;

-- ---------------------------------------------------------------------------------------------
-- Default group for a new column
-- ---------------------------------------------------------------------------------------------

-- Applied once, on INSERT, and only when the insert did not say which group it wants. Without it
-- every column created after this migration would be ungrouped, including the ones the
-- assignment trigger creates, which the render-time heuristic used to group as soon as a second
-- one appeared. In order:
--
--   1. Inserted between two members of the same group: join that group ("add Quiz 3 between
--      Quiz 2 and Quiz 4"). Decided by position alone.
--   2. The column just before it is in the same family: join that column's group, or, if that
--      column is ungrouped, create a group for the two of them. This is what keeps a new
--      course's "Assignment 1, Assignment 2, ..." grouped.
--
-- Neither applies to a column computed from the columns it would join: an average of the
-- homework is a summary of the homework group, not one more homework (the backfill's F9).
--
-- Membership is never recomputed afterwards: an UPDATE never runs this, so moving or renaming a
-- column leaves its group alone, and an instructor's choice always wins. The position is worked
-- out here (an unset sort_order means "append"), so this does not depend on firing before or
-- after gradebook_columns_enforce_sort_order_tr.
CREATE OR REPLACE FUNCTION public.gradebook_columns_inherit_group()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_pos integer;
  v_before public.gradebook_columns;
  v_after_group bigint;
  v_class_id bigint;
  v_stem_before text;
  v_stem_new text;
  v_group_id bigint;
  v_deps bigint[] := COALESCE(public.gradebook_column_dependency_ids(NEW.dependencies), '{}');
BEGIN
  IF NEW.group_id IS NOT NULL THEN
    RETURN NEW;
  END IF;

  IF NEW.sort_order IS NOT NULL THEN
    v_pos := GREATEST(NEW.sort_order, 0);
  ELSIF current_setting('pawtograder.bypass_sort_order_trigger_' || NEW.gradebook_id, true) = 'true' THEN
    -- A bulk write that leaves sort_order unset is deciding the layout itself.
    RETURN NEW;
  ELSE
    SELECT COALESCE(max(sort_order), -1) + 1 INTO v_pos
    FROM public.gradebook_columns
    WHERE gradebook_id = NEW.gradebook_id AND id <> NEW.id;
  END IF;

  SELECT * INTO v_before
  FROM public.gradebook_columns
  WHERE gradebook_id = NEW.gradebook_id AND id <> NEW.id AND sort_order < v_pos
  ORDER BY sort_order DESC, id DESC
  LIMIT 1;

  IF v_before.id IS NULL THEN
    RETURN NEW;
  END IF;

  -- 1. Between two members of one group. (Before the sort_order trigger shifts the columns at or
  -- after v_pos, the next one is at v_pos; after, it is at v_pos + 1. Either way it is the first
  -- column at or after v_pos.)
  SELECT group_id INTO v_after_group
  FROM public.gradebook_columns
  WHERE gradebook_id = NEW.gradebook_id AND id <> NEW.id AND sort_order >= v_pos
  ORDER BY sort_order, id
  LIMIT 1;

  -- A summary of the group it would join stays out of it.
  IF v_before.id = ANY (v_deps) OR (
    v_before.group_id IS NOT NULL AND EXISTS (
      SELECT 1 FROM public.gradebook_columns WHERE group_id = v_before.group_id AND id = ANY (v_deps)
    )
  ) THEN
    RETURN NEW;
  END IF;

  IF v_before.group_id IS NOT NULL AND v_before.group_id = v_after_group THEN
    NEW.group_id := v_before.group_id;
    RETURN NEW;
  END IF;

  -- 2. Same family as the column just before it.
  IF public.gradebook_column_family(v_before.slug) IS DISTINCT FROM public.gradebook_column_family(NEW.slug) THEN
    RETURN NEW;
  END IF;

  IF v_before.group_id IS NOT NULL THEN
    NEW.group_id := v_before.group_id;
    RETURN NEW;
  END IF;

  v_stem_before := public.gradebook_column_name_stem(v_before.name);
  v_stem_new := public.gradebook_column_name_stem(NEW.name);

  SELECT class_id INTO v_class_id FROM public.gradebooks WHERE id = NEW.gradebook_id;

  INSERT INTO public.gradebook_column_groups (class_id, gradebook_id, name)
  VALUES (
    v_class_id,
    NEW.gradebook_id,
    public.gradebook_column_group_free_name(
      NEW.gradebook_id,
      CASE
        WHEN v_stem_before = v_stem_new AND v_stem_new <> '' THEN v_stem_new
        ELSE public.gradebook_column_family_title(public.gradebook_column_family(NEW.slug))
      END
    )
  )
  RETURNING id INTO v_group_id;

  UPDATE public.gradebook_columns SET group_id = v_group_id WHERE id = v_before.id;
  NEW.group_id := v_group_id;
  RETURN NEW;
END;
$$;

CREATE TRIGGER gradebook_columns_inherit_group_tr
  BEFORE INSERT ON public.gradebook_columns
  FOR EACH ROW
  EXECUTE FUNCTION public.gradebook_columns_inherit_group();

-- ---------------------------------------------------------------------------------------------
-- The two existing functions that rewrite the whole order
-- ---------------------------------------------------------------------------------------------

-- gradebook_columns_reorder: the checks are unchanged from 20260406120000. The write now goes
-- through gradebook_columns_apply_order, so it touches only the rows that move, keeps groups
-- whole, and sends one realtime message per channel instead of one per row per student.
CREATE OR REPLACE FUNCTION public.gradebook_columns_reorder(p_ordered_column_ids bigint[])
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_gradebook_id bigint;
  v_class_id bigint;
  v_expected_count integer;
  v_payload_count integer;
  v_distinct_payload integer;
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'Not authenticated';
  END IF;

  v_payload_count := COALESCE(array_length(p_ordered_column_ids, 1), 0);

  IF v_payload_count = 0 THEN
    RETURN;
  END IF;

  SELECT COUNT(DISTINCT x) INTO v_distinct_payload
  FROM unnest(p_ordered_column_ids) AS x;

  IF v_distinct_payload <> v_payload_count THEN
    RAISE EXCEPTION 'Duplicate column IDs in reorder payload';
  END IF;

  SELECT gc.gradebook_id INTO v_gradebook_id
  FROM public.gradebook_columns AS gc
  WHERE gc.id = p_ordered_column_ids[1];

  IF v_gradebook_id IS NULL THEN
    RAISE EXCEPTION 'gradebook column % not found', p_ordered_column_ids[1];
  END IF;

  SELECT class_id INTO v_class_id
  FROM public.gradebooks
  WHERE id = v_gradebook_id;

  IF v_class_id IS NULL THEN
    RAISE EXCEPTION 'gradebook % not found', v_gradebook_id;
  END IF;

  IF NOT public.authorizeforclassinstructor(v_class_id) THEN
    RAISE EXCEPTION 'insufficient permissions: instructor access required for class %', v_class_id;
  END IF;

  -- Single-key form (bigint); the two-key form requires (integer, integer), not (int, bigint).
  -- Same namespace as every other writer of column order, so all of them serialize per gradebook.
  PERFORM pg_advisory_xact_lock(v_gradebook_id);

  SELECT COUNT(*)::integer INTO v_expected_count
  FROM public.gradebook_columns
  WHERE gradebook_id = v_gradebook_id;

  IF v_expected_count <> v_payload_count THEN
    RAISE EXCEPTION 'Payload count (%) does not match gradebook column count (%)', v_payload_count, v_expected_count;
  END IF;

  IF (
    SELECT COUNT(*)::integer
    FROM public.gradebook_columns
    WHERE gradebook_id = v_gradebook_id
      AND id = ANY (p_ordered_column_ids)
  ) <> v_payload_count THEN
    RAISE EXCEPTION 'One or more column IDs do not belong to this gradebook';
  END IF;

  PERFORM public.gradebook_columns_apply_order(v_gradebook_id, p_ordered_column_ids);
END;
$$;

-- gradebook_auto_layout: the layout algorithm is unchanged from 20250811000001. What changed:
--   * It takes the same per-gradebook lock as every other writer of column order (it used a
--     separate two-key lock, so it could interleave with a reorder; the ::int cast in that lock
--     also failed for gradebook ids above 2^31).
--   * Dependency ids that are not whole numbers are skipped instead of failing a cast.
--   * The final pass keeps groups whole, and clients get one realtime message per channel for
--     the columns that actually moved, instead of one per row per student.
CREATE OR REPLACE FUNCTION public.gradebook_auto_layout(p_gradebook_id bigint)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE
  v_col record;
  v_dep_col_id bigint;
  v_max_dep_order integer;
  v_new_order integer;
  v_processed_ids bigint[] := '{}';
  v_remaining_count integer;
  v_prev_remaining_count integer := -1;
  v_class_id bigint;
  v_before jsonb;
  v_moved bigint[];
BEGIN
  SELECT class_id INTO v_class_id
  FROM public.gradebooks
  WHERE id = p_gradebook_id;

  IF v_class_id IS NULL THEN
    RAISE EXCEPTION 'gradebook % not found', p_gradebook_id;
  END IF;

  IF NOT public.authorizeforclassinstructor(v_class_id) THEN
    RAISE EXCEPTION 'insufficient permissions: instructor access required for class %', v_class_id;
  END IF;

  PERFORM pg_advisory_xact_lock(p_gradebook_id);

  SELECT jsonb_object_agg(id, sort_order) INTO v_before
  FROM public.gradebook_columns
  WHERE gradebook_id = p_gradebook_id;

  PERFORM set_config('pawtograder.bypass_sort_order_trigger_' || p_gradebook_id, 'true', true);
  PERFORM set_config('pawtograder.batch_column_broadcast_' || p_gradebook_id, 'true', true);

  -- Step 1: Initial alphanumeric sort by slug (lab-2 before lab-10)
  WITH ordered_cols AS (
    SELECT id, (ROW_NUMBER() OVER (ORDER BY
      regexp_replace(slug, '\d+', '', 'g'),
      COALESCE((regexp_match(slug, '\d+'))[1]::integer, 0),
      slug
    ) - 1)::integer AS temp_sort_order
    FROM public.gradebook_columns
    WHERE gradebook_id = p_gradebook_id
  )
  UPDATE public.gradebook_columns gc
  SET sort_order = oc.temp_sort_order
  FROM ordered_cols oc
  WHERE gc.id = oc.id
    AND gc.sort_order IS DISTINCT FROM oc.temp_sort_order;

  -- Step 2: Topological sort to respect gradebook_column dependencies
  LOOP
    SELECT COUNT(*) INTO v_remaining_count
    FROM public.gradebook_columns
    WHERE gradebook_id = p_gradebook_id
      AND id <> ALL(v_processed_ids);

    EXIT WHEN v_remaining_count = 0;

    IF v_remaining_count = v_prev_remaining_count THEN
      RAISE WARNING 'Circular dependency detected in gradebook %. Stopping topological sort.', p_gradebook_id;
      EXIT;
    END IF;
    v_prev_remaining_count := v_remaining_count;

    FOR v_col IN
      SELECT id, slug, public.gradebook_column_dependency_ids(dependencies) AS dep_ids, sort_order
      FROM public.gradebook_columns
      WHERE gradebook_id = p_gradebook_id
        AND id <> ALL(v_processed_ids)
      ORDER BY sort_order NULLS LAST, id
    LOOP
      IF COALESCE(cardinality(v_col.dep_ids), 0) > 0 THEN

        v_max_dep_order := -1;

        FOREACH v_dep_col_id IN ARRAY v_col.dep_ids
        LOOP
          IF v_dep_col_id = ANY(v_processed_ids) THEN
            SELECT sort_order INTO v_new_order
            FROM public.gradebook_columns
            WHERE id = v_dep_col_id AND gradebook_id = p_gradebook_id;

            IF v_new_order IS NOT NULL AND v_new_order > v_max_dep_order THEN
              v_max_dep_order := v_new_order;
            END IF;
          END IF;
        END LOOP;

        IF EXISTS (
          SELECT 1
          FROM unnest(v_col.dep_ids) AS dep_id
          WHERE dep_id <> ALL(v_processed_ids)
            AND EXISTS (
              SELECT 1 FROM public.gradebook_columns
              WHERE id = dep_id AND gradebook_id = p_gradebook_id
            )
        ) THEN
          CONTINUE;
        END IF;

        IF v_max_dep_order >= 0 THEN
          v_new_order := v_max_dep_order + 1;
          UPDATE public.gradebook_columns
          SET sort_order = v_new_order
          WHERE id = v_col.id;
        END IF;
      END IF;

      v_processed_ids := array_append(v_processed_ids, v_col.id);
    END LOOP;
  END LOOP;

  -- Final pass: compact to 0..n-1 with every group's members adjacent.
  PERFORM public.gradebook_columns_make_groups_contiguous(p_gradebook_id);

  PERFORM set_config('pawtograder.batch_column_broadcast_' || p_gradebook_id, 'false', true);
  PERFORM set_config('pawtograder.bypass_sort_order_trigger_' || p_gradebook_id, 'false', true);

  SELECT array_agg(id ORDER BY id) INTO v_moved
  FROM public.gradebook_columns
  WHERE gradebook_id = p_gradebook_id
    AND sort_order IS DISTINCT FROM (v_before ->> id::text)::integer;

  PERFORM public.gradebook_columns_broadcast_order(p_gradebook_id, v_moved);
END;
$function$;

-- ---------------------------------------------------------------------------------------------
-- Backfill
--
-- Reads slugs, names and dependencies once per gradebook, so nothing has to read them at render
-- time again. It is a function rather than inline SQL for one reason: a gradebook that exists
-- before this migration is backfilled by the migration, but `supabase db reset` replays
-- migrations into an empty database and seeds afterwards, and the seed has to leave its class
-- in the same state a pre-existing course would be in. scripts/DatabaseSeedingUtils.ts calls it
-- once, after it has created its columns. The app never calls it; only service_role can.
--
-- It only touches gradebooks that have no groups yet, so running it twice is a no-op and it
-- can never overwrite a grouping an instructor has since edited.
--
-- It starts from exactly what the render-time heuristic produced and departs from it only where
-- the heuristic was wrong; each departure is labelled (F1, F2, F3, F4, F6, F8, F9) and listed in the PR.
--
--   1. Order each gradebook's columns by (sort_order, id) and give each a position 1..n. A NULL
--      sort_order counts as 0 here, as everywhere, but no longer collides with another column,
--      because position is decided by (sort_order, id) (F6).
--   2. Family = the heuristic's prefix: "assignment-<type>" for assignment-<type>-*, otherwise
--      everything before the first "-".
--   3. A family run is consecutive positions with the same family. The heuristic also cut a run
--      wherever sort_order skipped a value; positions don't, so a hole left by a deleted column
--      no longer splits a family in two (F1). A column computed from other members of its own
--      run is their summary, not their sibling ("final-grade" computed from "final-exam"), so it
--      leaves the run and is treated like any other lone computed column (F9).
--   4. Columns left on their own after step 3 that are computed from exactly the same set of
--      columns, and sit next to each other, form one run (F4).
--   5. Every run of two or more columns becomes a group. A run of one stays ungrouped, which is
--      what it rendered as.
--   6. Name: the common stem of the member columns' display names (minus a trailing "(...)" and
--      number), so "AI Usage Log 1/2" gives "AI Usage Log", not "Ai" (F3). Failing that, the
--      heuristic's own title. A run of computed columns is named after the group its inputs
--      are all in ("Skill summary"), failing that "Summary".
--   7. Names are unique per gradebook: a family interrupted by some other column stays two
--      groups, because merging them would move columns, but the second is "Quiz (2)" and no
--      longer shares the first one's collapse state (F2). Every candidate is checked against
--      every name already taken, including other generated ones.
--
-- Policy for rows it can't classify: none are dropped and none are moved. A column whose slug
-- has no "-" is its own family, exactly as before; anything that ends up alone is ungrouped; a
-- dependency entry that isn't a column id is ignored. The backfill never changes sort_order.
-- ---------------------------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.gradebook_column_groups_backfill(p_gradebook_id bigint DEFAULT NULL)
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_created integer := 0;
  v_group record;
  v_group_id bigint;
BEGIN
  -- Qualified with pg_temp throughout: this runs as the table owner, and an unqualified name
  -- would resolve to a public table of the same name first.
  DROP TABLE IF EXISTS pg_temp._gcg_columns, pg_temp._gcg_runs, pg_temp._gcg_groups;

  CREATE TEMP TABLE _gcg_columns AS
  SELECT
    gc.id,
    gc.gradebook_id,
    g.class_id,
    row_number() OVER (PARTITION BY gc.gradebook_id ORDER BY COALESCE(gc.sort_order, 0), gc.id) AS pos,
    public.gradebook_column_family(gc.slug) AS family,
    public.gradebook_column_dependency_ids(gc.dependencies) AS deps,
    public.gradebook_column_name_stem(gc.name) AS stem
  FROM public.gradebook_columns gc
  JOIN public.gradebooks g ON g.id = gc.gradebook_id
  WHERE (p_gradebook_id IS NULL OR gc.gradebook_id = p_gradebook_id)
    AND NOT EXISTS (SELECT 1 FROM public.gradebook_column_groups x WHERE x.gradebook_id = gc.gradebook_id);

  -- Step 3, first pass: family runs by position, then take out every column that is computed
  -- from another member of its own run (it becomes a family of its own).
  WITH first_runs AS (
    SELECT
      x.id,
      x.gradebook_id,
      sum(CASE WHEN x.family IS DISTINCT FROM x.prev_family THEN 1 ELSE 0 END)
        OVER (PARTITION BY x.gradebook_id ORDER BY x.pos) AS family_run
    FROM (
      SELECT c.*, lag(c.family) OVER (PARTITION BY c.gradebook_id ORDER BY c.pos) AS prev_family
      FROM pg_temp._gcg_columns c
    ) x
  ),
  summaries AS (
    SELECT DISTINCT c.id
    FROM pg_temp._gcg_columns c
    JOIN first_runs fr ON fr.id = c.id
    JOIN first_runs sib ON sib.gradebook_id = fr.gradebook_id AND sib.family_run = fr.family_run AND sib.id <> c.id
    WHERE sib.id = ANY (c.deps)
  )
  UPDATE pg_temp._gcg_columns c
  SET family = 'summary:' || c.id
  FROM summaries s
  WHERE s.id = c.id;

  -- Steps 3 and 4. A unit is a family run (if it has 2+ members), a set of inputs (for a lone
  -- computed column), or the column itself; consecutive columns with the same unit key are a run.
  CREATE TEMP TABLE _gcg_runs AS
  WITH family_runs AS (
    SELECT
      x.*,
      sum(CASE WHEN x.family IS DISTINCT FROM x.prev_family THEN 1 ELSE 0 END)
        OVER (PARTITION BY x.gradebook_id ORDER BY x.pos) AS family_run
    FROM (
      SELECT c.*, lag(c.family) OVER (PARTITION BY c.gradebook_id ORDER BY c.pos) AS prev_family
      FROM pg_temp._gcg_columns c
    ) x
  ),
  units AS (
    SELECT
      fr.*,
      CASE
        WHEN count(*) OVER (PARTITION BY fr.gradebook_id, fr.family_run) > 1 THEN 'family:' || fr.family_run
        WHEN fr.deps IS NOT NULL THEN 'derived:' || fr.deps::text
        ELSE 'column:' || fr.id
      END AS unit_key
    FROM family_runs fr
  ),
  runs AS (
    SELECT
      k.*,
      sum(CASE WHEN k.unit_key IS DISTINCT FROM k.prev_unit_key THEN 1 ELSE 0 END)
        OVER (PARTITION BY k.gradebook_id ORDER BY k.pos) AS run
    FROM (
      SELECT u.*, lag(u.unit_key) OVER (PARTITION BY u.gradebook_id ORDER BY u.pos) AS prev_unit_key
      FROM units u
    ) k
  )
  SELECT r.*, count(*) OVER (PARTITION BY r.gradebook_id, r.run) AS run_size
  FROM runs r;

  -- Steps 5 and 6.
  CREATE TEMP TABLE _gcg_groups AS
  SELECT
    r.gradebook_id,
    min(r.class_id) AS class_id,
    r.run,
    min(r.pos) AS first_pos,
    bool_or(r.unit_key LIKE 'derived:%') AS is_derived,
    CASE
      WHEN count(DISTINCT r.stem) = 1 AND min(r.stem) <> '' THEN min(r.stem)
      ELSE public.gradebook_column_family_title(min(r.family))
    END AS name,
    NULL::bigint AS group_id
  FROM pg_temp._gcg_runs r
  WHERE r.run_size > 1
  GROUP BY r.gradebook_id, r.run;

  -- A run of computed columns is named after the one non-derived group all of its inputs are in.
  UPDATE pg_temp._gcg_groups dg
  SET name = COALESCE(
    (
      SELECT src.name || ' summary'
      FROM pg_temp._gcg_runs m
      CROSS JOIN LATERAL unnest(m.deps) AS dep(id)
      JOIN pg_temp._gcg_runs d ON d.id = dep.id
      JOIN pg_temp._gcg_groups src ON src.gradebook_id = d.gradebook_id AND src.run = d.run AND NOT src.is_derived
      WHERE m.gradebook_id = dg.gradebook_id AND m.run = dg.run
      GROUP BY src.name
      HAVING count(*) = (
        SELECT count(*) FROM pg_temp._gcg_runs m2 CROSS JOIN LATERAL unnest(m2.deps)
        WHERE m2.gradebook_id = dg.gradebook_id AND m2.run = dg.run
      )
    ),
    'Summary'
  )
  WHERE dg.is_derived;

  -- Step 7, one group at a time in left-to-right order, so every name is checked against every
  -- name taken before it.
  FOR v_group IN
    SELECT gradebook_id, class_id, run, name FROM pg_temp._gcg_groups ORDER BY gradebook_id, first_pos
  LOOP
    INSERT INTO public.gradebook_column_groups (class_id, gradebook_id, name)
    VALUES (
      v_group.class_id,
      v_group.gradebook_id,
      public.gradebook_column_group_free_name(v_group.gradebook_id, v_group.name)
    )
    RETURNING id INTO v_group_id;

    UPDATE pg_temp._gcg_groups
    SET group_id = v_group_id
    WHERE gradebook_id = v_group.gradebook_id AND run = v_group.run;

    v_created := v_created + 1;
  END LOOP;

  UPDATE public.gradebook_columns gc
  SET group_id = g.group_id
  FROM pg_temp._gcg_runs r
  JOIN pg_temp._gcg_groups g ON g.gradebook_id = r.gradebook_id AND g.run = r.run
  WHERE gc.id = r.id;

  DROP TABLE pg_temp._gcg_columns, pg_temp._gcg_runs, pg_temp._gcg_groups;
  RETURN v_created;
END;
$$;

-- ---------------------------------------------------------------------------------------------
-- Privileges on functions. Everything above is internal: triggers, the backfill (service_role
-- only) and the RPCs in 20260924045931 call it as the owner. gradebook_columns_reorder and
-- gradebook_auto_layout keep the grants they already had.
-- ---------------------------------------------------------------------------------------------

REVOKE ALL ON FUNCTION public.gradebook_columns_display_order(bigint) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.gradebook_column_groups_torn(bigint) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.gradebook_columns_order_payload(bigint, bigint[], text) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.gradebook_columns_broadcast_order(bigint, bigint[]) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.gradebook_columns_write_order(bigint, bigint[]) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.gradebook_columns_make_groups_contiguous(bigint) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.gradebook_columns_apply_order(bigint, bigint[]) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.gradebook_column_group_clean_name(text) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.gradebook_column_family(text) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.gradebook_column_name_stem(text) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.gradebook_column_family_title(text) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.gradebook_column_group_free_name(bigint, text) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.gradebook_column_dependency_ids(jsonb) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.gradebook_column_groups_backfill(bigint) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.gradebook_column_groups_backfill(bigint) TO service_role;

-- Every gradebook that exists now. The row-level column broadcast is suspended for this one
-- call: it would send one realtime message per column per student in every course, and clients
-- running the previous frontend don't read group_id anyway. Every other trigger (audit,
-- updated_at, cache invalidation) still fires.
ALTER TABLE public.gradebook_columns DISABLE TRIGGER broadcast_gradebook_columns_unified;
SELECT public.gradebook_column_groups_backfill();
ALTER TABLE public.gradebook_columns ENABLE TRIGGER broadcast_gradebook_columns_unified;
